# Generated by Django 4.2.6 on 2023-11-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence_limit_per_month', models.CharField(max_length=50)),
                ('current_expence_amount', models.CharField(max_length=50)),
                ('reward_price', models.IntegerField(max_length=11)),
                ('reward_calculated_till', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('date', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expence_tracker.expencecategory')),
            ],
        ),
    ]
