# Generated by Django 4.2.6 on 2023-11-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expencemaster',
            name='reward_price',
            field=models.IntegerField(),
        ),
    ]
