# Generated by Django 4.2.6 on 2023-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0002_alter_expence_price_alter_expencemaster_reward_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expencemaster',
            name='expence_limit_per_day',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
